# Class built for state_get_balance RPC call
package GetBalance::GetBalanceResultRPC;
use LWP::UserAgent;
use Data::Dumper;
use Common::ErrorException;
use GetBalance::GetBalanceResult;
use JSON qw( decode_json );
sub new {
	my $class = shift;
	my $self = {_url=>shift}; # This url can be test net, main net or local host for sending the POST method for RPC call
	bless $self, $class;
	return $self;
}

# get-set method for _url
sub setUrl {
	my ($self,$value) = @_;
	$self->{_url} = $value if defined ($value);
	return $self->{_url};
}
sub getUrl {
	my ($self) = @_;
	return $self->{_url};
}
=comment
     * This function initiate the process of sending POST request with given parameter in JSON string format
     * The input parameterStr is used to send to server as parameter of the POST request to get the result back.
     * The input parameterStr is somehow like this:
     * {"method" : "state_get_balance","id" : 1,"params" :{"state_root_hash" : "8b463b56f2d124f43e7c157e602e31d5d2d5009659de7f1e79afbd238cbaa189","purse_uref":"uref-be1dc0fd639a3255c1e3e5e2aa699df66171e40fa9450688c5d718b470e057c6-007"},"jsonrpc" : "2.0"}
     * This string in generated by the class GetBalanceParams
     * Output: GetBalanceResult is retrieved by parsing JsonObject result
     * If the result is error,  then an exception is thrown
     * Else the GetBalanceResult is taken by parsing the retrieving JsonObject
=cut
sub getBalance {
	my ($self) = @_;
	my @list = @_;
	my $uri = $self->{_url};
	if($uri) {
	} else {
		$uri = $Common::ConstValues::TEST_NET;
	}
	my $json = $list[1];
	my $req = HTTP::Request->new( 'POST', $uri );
	$req->header( 'Content-Type' => 'application/json');
	$req->content( $json );
	my $lwp = LWP::UserAgent->new;
	my $response = $lwp->request( $req );
	if ($response->is_success) {
	    my $d = $response->decoded_content;
	    my $decoded = decode_json($d);
	    my $errorCode = $decoded->{'error'}{'code'};
	    if($errorCode) {
	    	my $errorException = new Common::ErrorException();
	    	$errorException->setErrorCode($errorCode);
	    	$errorException->setErrorMessage($decoded->{'error'}{'message'});
	    	return $errorException;
	    } else {
		    my $ret = GetBalance::GetBalanceResult->fromJsonToGetBalanceResult($decoded->{'result'});
		   	return $ret;
	    }
	}
	else {
	    die $response->status_line;
	}
}
1;