# Class built for chain_get_block_transfers RPC call
package GetBlockTransfers::GetBlockTransfersRPC;
use LWP::UserAgent;
use Data::Dumper;
use Common::ErrorException;
use JSON qw( decode_json );
sub new {
	my $class = shift;
	my $self = {_url=>shift}; # This url can be test net, main net or local host for sending the POST method for RPC call
	bless $self, $class;
	return $self;
}

=comment
	 * This function initiate the process of sending POST request with given parameter in JSON string format
     * The input parameterStr is used to send to server as parameter of the POST request to get the result back.
     * The input parameterStr is somehow like this:
     * {"params" :  [], "id" :  1, "method": "chain_get_block_transfers", "jsonrpc" :  "2.0"}
     * if you wish to send without any param along with the RPC call
     * or:
     * {"method" :  "chain_get_block_transfers", "id" :  1, "params" :  {"block_identifier" :  {"Hash" : "d16cb633eea197fec519aee2cfe050fe9a3b7e390642ccae8366455cc91c822e"}}, "jsonrpc" :  "2.0"}
     * if you wish to send the block hash along with the POST method in the RPC call
     * or:
     * {"method" :  "chain_get_block_transfers", "id" :  1, "params" :  {"block_identifier" :  {"Height" : 100}}, "jsonrpc" :  "2.0"}
     * if you wish to send the block height along with the POST method in the RPC call
     * The parameterStr is generated by the BlockIdentifier class, declared in file Common::BlockIdentifier.pm
     * Then the GetBlockTransfersResult is retrieved by parsing JsonObject result
     * If the result is error,  then an exception is thrown
     * Else the GetBlockTransfersResult is taken by parsing the retrieving JsonObject
=cut
sub getBlockTransfers {
	my @list = @_;
	my $uri = 'https://node-clarity-testnet.make.services/rpc';
	my $json = $list[1];
	my $req = HTTP::Request->new( 'POST', $uri );
	$req->header( 'Content-Type' => 'application/json');
	$req->content( $json );
	my $lwp = LWP::UserAgent->new;
	my $response = $lwp->request( $req );
	if ($response->is_success) {
	    my $d = $response->decoded_content;
	    my $decoded = decode_json($d);
	    my $errorCode = $decoded->{'error'}{'code'};
	    if($errorCode) {
	    	my $errorException = new Common::ErrorException();
	    	$errorException->setErrorCode($errorCode);
	    	$errorException->setErrorMessage($decoded->{'error'}{'message'});
	    	return $errorException;
	    } else {
		    my $ret = GetBlockTransfers::GetBlockTransfersResult->fromJsonObjectToGetBlockTransfersResult($decoded->{'result'});
		   	return $ret;
	    }
	}
	else {
	    die $response->status_line;
	}
}
1;